name: Discord announcement on release

on:
  release:
    types: [published]

jobs:
  discord_announcement:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord webhook notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_ANNOUNCEMENTS_WEBHOOK_URL }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          PAYLOAD=$(jq -nc \
            --arg title "New WalterModem release: $RELEASE_NAME" \
            --arg description "$RELEASE_BODY" \
            --arg url "$RELEASE_URL" \
            '{
              embeds: [{
                title: $title,
                description: $description,
                url: $url,
                color: 99975,
                fields: [
                  {
                    name: "Repo Tag",
                    value: $ARGS.named.tag,
                    inline: true
                  }
                ]
              }]
            }' \
            --arg tag "$RELEASE_TAG")
          
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$WEBHOOK_URL"
